# Generated by Django 2.0.7 on 2018-11-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment_system', '0002_auto_20181114_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='for_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_level',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
