# Generated by Django 2.0.7 on 2018-11-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment_system', '0003_auto_20181115_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
