# Generated by Django 2.0.7 on 2018-11-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment_system', '0004_auto_20181115_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
