# Generated by Django 2.0.7 on 2018-11-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment_system', '0005_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
