# Generated by Django 2.0.7 on 2018-11-15 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment_system', '0009_auto_20181115_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='for_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
