# Generated by Django 2.0.7 on 2019-01-16 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment_system', '0014_auto_20181119_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='for_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_comments', to='managment_system.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='managment_system.User'),
        ),
    ]
