# Generated by Django 2.0.7 on 2019-01-16 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment_system', '0015_auto_20190116_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_comments', to='managment_system.Message'),
        ),
    ]
